name: commit gha files test

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - .github/workflows/commit-gha.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/commit-gha.yaml

jobs:
  v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat /dev/random | head | base64 > .github/workflows/random.txt
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/workflows/random.txt
          git commit -m 'random.txt'
          git push

