name: dispatch dispatch test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - .github/workflows/dispatch-dispatch.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/dispatch-dispatch.yaml

jobs:
  v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow run comment.yaml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh run list --workflow=comment.yaml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


