name: find-pr test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/find-pr.yaml
jobs:
  find-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Find Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: find-pull-request
        with:
          state: all

      - run: echo "Pull Request ${number}"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}

